name: PNPM Build and Deploy to GitHub Pages

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  deploy:
    uses: importantimport/.github/.github/workflows/pnpm-gh-pages.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
