name: PNPM Build and Deploy to GitHub Pages

on:
  workflow_call:
    inputs:
      fetch-depth:
        default: 0
        required: false
        type: number

      node-version:
        default: latest
        required: false
        type: string

      pnpm-version:
        default: latest
        required: false
        type: string

      cname:
        required: false
        type: string

      publish_dir:
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Install
        uses: importantimport/.github/.github/workflows/pnpm-install.yml@main
        with:
          fetch-depth: ${{ inputs.fetch-depth }}
          node-version: ${{ inputs.node-version }}
          pnpm-version: ${{ inputs.pnpm-version }}

      - name: Build
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ inputs.publish_dir }}
          cname: ${{ inputs.cname }}
