name: PNPM Build and Deploy to GitHub Pages

on:
  workflow_call:
    inputs:
      fetch-depth:
        default: 0
        required: false
        type: number

      node-version:
        default: latest
        required: false
        type: string

      cname:
        required: false
        type: string

      publish_dir:
        required: false
        type: string
        
      build_command:
        default: pnpm build
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.fetch-depth }}
      - uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: ${{ inputs.node-version }}
      - run: pnpm install --frozen-lockfile
      - run: ${{ inputs.build_command }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ inputs.publish_dir }}
          cname: ${{ inputs.cname }}
